### ISSUE TITLE
PinMapper.html - Not responding on macOS

### ISSUE THREAD

**Issue by markmcgookin** [akaenner/Badger2040Keypad#1]
When I open pinmapper.html on Safari, Edge or Chrome on macOS the page loads fine, but I never am able to set the pins, no matter what I type, no values show up, and thus I am unable to download any mapping files.

**Comment by markmcgookin** [comment]
I've been following the tutorial on your website and am building out the keyboard now, so was hoping to get the software up and running while I wait for the keys/MCP23017 to arrive in the next day or two.

**Comment by akaenner** [comment]
ah ok. You can simulate key input in PinMapper.html by pressing a number key on you regular keyboard and then press the enter key.
